from datetime import datetime
import time
dob = input("Enter DOB, use dd/mm/yyyy format: ")
dob = datetime.strptime(dob, '%d/%m/%Y')
print ("")
print("Here are your age statistics...")
print ("")
time.sleep(2)
print ("Years : %d" % ((datetime.today() - dob).days/365))
print ("")
print ("Months : %d" % ((datetime.today() - dob).days/30))
print ("")
print ("Hours : %d" % ((datetime.today() - dob).days*24))
print ("")
print ("Minutes : %d" % ((datetime.today() - dob).days*1440))
print ("")
print ("Seconds : %d" % ((datetime.today() - dob).days*86400))
print ("")
print ("Thank You")
